FROM --platform=linux/amd64 bde2020/hive:latest
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN mv /etc/apt/sources.list /etc/apt/sources.list.backup
RUN mv /etc/apt/sources.list.d /etc/apt/sources.list.d.backup
RUN mkdir /etc/apt/sources.list.d
RUN cp /usr/share/doc/apt/examples/sources.list /etc/apt/sources.list
RUN apt update && apt install wget -y
RUN wget https://archive.apache.org/dist/sqoop/1.4.7/sqoop-1.4.7.bin__hadoop-2.6.0.tar.gz
RUN mkdir sqoop
RUN tar -xzvf sqoop-1.4.7.bin__hadoop-2.6.0.tar.gz
RUN mv sqoop-1.4.7.bin__hadoop-2.6.0 sqoop/
RUN rm -r sqoop-1.4.7.bin__hadoop-2.6.0.tar.gz
RUN echo "export SQOOP_HOME=/opt/sqoop/sqoop-1.4.7.bin__hadoop-2.6.0" >> ~/.bashrc
RUN echo "export PATH=$PATH:/opt/sqoop/sqoop-1.4.7.bin__hadoop-2.6.0/bin" >> ~/.bashrc
RUN source ~/.bashrc
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
RUN apt install apt-transport-https -y
RUN apt update && ACCEPT_EULA=Y apt install -y --force-yes mssql-tools 
RUN apt install -y --force-yes unixodbc-dev 
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN source ~/.bashrc